package de.skat3.network.datatypes;

public enum MessageType {
    
    COMMAND_ACTION, COMMAND_INFO, ANWSER_ACTION, CONNECTION_OPEN, CONNECTION_CLOSE, CHAT_MESSAGE, LOBBY_QUESTION, LOBBY_ANSWER;
  
}
